# Use postgres/example user/password credentials
version: '3.1'

services:
 
    db_grafana:
        image: postgres
        restart: always
        container_name: grafana_db
        environment:
            POSTGRES_PASSWORD: admin
        volumes:
            - ./database:/var/lib/postgresql/data
            - ./dumps:/dumps
            - ./scripts:/scripts
        ports:
            - "5434:5432"     
    web_grafana:
        image: grafana/grafana
        restart: always
        container_name: grafana_web
        volumes:
            - ./dashboard:/dashboard
        ports:
            - "3001:3000"
           
           