# Use postgres/example user/password credentials
version: '3.1'

services:
 
    db_grafana:
        image: postgres
        restart: always
        container_name: grafana_db
        environment:
            POSTGRES_PASSWORD: admin
        volumes:
            - type: bind
              source: "./database" 
              target: "/var/lib/postgresql/data"
            - type: bind
              source: "./dumps"
              target: "/dumps"
        ports:
            - "5434:5432"     
            
           