 # Use postgres/example user/password credentials
version: '3.1'

services:
 
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
        volumes:
            - type: bind
              source: "./database" 
              target: "/var/lib/postgresql/data"
        ports:
            - "5433:5432"     
    
