# Use postgres/example user/password credentials
version: '3.1'

services:
 
    db_emergency:
        image: postgres
        restart: always
        container_name: emergency_db
        environment:
            POSTGRES_PASSWORD: admin
        volumes:
            - type: bind
              source: "./database" 
              target: "/var/lib/postgresql/data"
        ports:
            - "5433:5432"     
            
            
    mqtt:
        image: eclipse-mosquitto
        restart: always
        container_name: emergency_mqtt
        ports:
          - 1883:1883
          - 9001:9001
        volumes:
            - type: bind
              source: "./log" 
              target: "/mosquitto/log"